### ISSUE TITLE
[Android] Compile Error: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536

### ISSUE THREAD

**Issue by dannyyaou** [mybigday/react-native-s3#36]
Thanks for the library first, this library is awesome!
But the package of s3 is actually very big 
and there's a limitation of methods while building app of android which is 65536
so I encounter this error:

`:app:dexDebug
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
Unknown source file : 	at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:502)
Unknown source file : 	at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:277)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:491)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:168)
Unknown source file : 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file : 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)`

Just wondering if any one else has the ploblem, and how do you guys solve it?

**Comment by ptmt** [comment]
See this http://www.methodscount.com/

I'm using that plugin to control the usage https://github.com/KeepSafe/dexcount-gradle-plugin

Also, after some level, the best option is to use Proguard builds (see you build.gradle and copy it from release and debug). You will need some configuration, adding namespaces and classes you use. 

My story optimizing:

react-native init
Total methods in app-debug.apk: 30685 (46.82% used)

before adding react-native-s3
Total methods in app-debug.apk: 57031 (87.02% used)

after proguard + s3
Total methods in app-debug.apk: 41996 (64.08% used)

Let me know if the blog post about it would be helpful for someone.
